# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "84113268652bb64dc6a80730f8039338"
name = "PandaForms"
application_url = "https://p01--pandaforms-app--77wd8gj6rv7k.code.run"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_products,read_themes,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/gdpr"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[auth]
redirect_urls = [ ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[app_proxy]
url = "https://p01--pandaforms-app--77wd8gj6rv7k.code.run/api"
subpath = "pandaforms"
prefix = "apps"
